development:
  host: '127.0.0.1:9200/'
  index: 'collection-explorer-dev'
production:
  host: <%= ENV.fetch('ELASTICSEARCH_PORT', '').gsub('tcp', 'http') %>
  index: 'collection-explorer'
test:
  host: '127.0.0.1:9200/'
  index: 'collection-explorer-test'
