development:
  sessions:
    default:
      database: explorer
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: explorer-test
      hosts:
        - localhost:27017
